### ISSUE TITLE
Push lxbuildenv.py into litex-buildenv?

### ISSUE THREAD

**Issue by mithro** [xobs/netv2-fpga#1]
LiteX-BuildEnv has a plan to replace [it's shell scripts](https://github.com/timvideos/litex-buildenv/tree/master/scripts) (and probably eventually Makefiles) with Python scripts. It looks like lxbuildenv.py is potentially a good start for that.

It would be good to see if we could push it back upstream?

**Comment by xobs** [comment]
Sure.

I'm not sure how "Pythonic" `lxbuildenv.py` is because it does things like re-exec()ing python and mucking about with paths.  It also now includes a `site.py` because the global `site.py` on Ubuntu at least prioritizes sitewide packages over local packages.  But now that `lxbuildenv.py` is a module that gets imported, perhaps the `site.py` package can be done away with...

The one problem I see, then, is the fact that the package now checks for Xilinx tools.  This is fine for the netv2 project, but do you have any recommendations on how to handle this on non-Xilinx platforms?

**Comment by xobs** [comment]
Also, it checks for a `riscv` gcc, which isn't so useful if you're building for `lm32`.

**Comment by mithro** [comment]
Should be pretty easy to genericize the gcc/Xilinx checks?

**Comment by xobs** [comment]
The bigger question is how to know which version of gcc / fpga toolchain to look for?  Right now it assumes riscv/xilinx.

I'll have to think on this some more...

**Comment by mithro** [comment]
Maybe just check of the current LiteX BuildEnv environment values and then fall back to the riscv / Vivado?

**Comment by xobs** [comment]
I'm not a fan of environment variables, because I feel they are too opaque.

How about bb72fc3efef9c0ad59f405c6b9af01c7a5ca3932? It looks for a Python variable called `LX_DEPENDENCIES`.  That makes it opt-in, allowing the module designer to define which features a particular project uses.  If you omit the value, it defaults to simply requiring Python 3.5.

**Comment by mithro** [comment]
I was thinking about it a bit and had a couple of ideas;

 * Maybe we should follow the [setup.cfg route that setuptools.py uses](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)?

 * Another option would be something like [`requirements.txt`](https://pip.pypa.io/en/stable/user_guide/#id1)

 * Another options would be the [environment.yml file that conda uses](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually)

LiteX-BuildEnv already has a [scripts/settings.sh file](https://github.com/timvideos/litex-buildenv/blob/master/scripts/settings.sh).

One important fact is that you can have multiple builds in the same litex-buildenv -- IE working on both the arty (which requires vivado) and opsis (which requires spartan 6) at the same time.

**Comment by mithro** [comment]
I also started something around trying to do better CI for LiteX and related stuff here -> https://github.com/mithro/liteci

**Comment by xobs** [comment]
I've explicitly tried to avoid doing those things because they're really really poorly documented for a beginner.

For example, in `litex`, when you try to run `setup.py` you're presented with no helpful information at all:

```sh
xobs@Cuboid:/mnt/d/Code/NeTV2/netv2-soc/deps/litex$ python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
xobs@Cuboid:/mnt/d/Code/NeTV2/netv2-soc/deps/litex$
```

Once you figure out that you need to somehow install `setuptools`, you can actually run the program, but it still won't give you any good information about what to do with litex:

```sh
C:\Python37\lib\site-packages\setuptools\dist.py:397: UserWarning: Normalizing '0.2.dev' to '0.2.dev0'
  normalized_version,
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

I'm not a fan of `requirements.txt` either for similar reasons -- when I first encountered it I thought it was a text file with the requirements, so I manually went through each file and installed it from the package manager.

Finally, I wanted to be able to work on submodules such as `litex` while they're under version control, without having to edit something in a `site-dist` directory.  `lxbuildenv` 

---

The way `lxbuilder.py` works is by foisting responsibility off onto the calling program.

In this repo, `netv2mvp.py` is the primary entrypoint.  In https://github.com/xobs/ws2812b-catcher the main entrypoint is `ws2812b-catcher.py`.  Each script has an `LX_DEPENDENCIES` variable in it that `lxbuildenv` looks for to figure out what requirements there are.

For arty and opsis, you'd create one or more `LX_DEPENDENCIES` variables and include things like "vivado", "webpack" and so on, plus the toolchains that are required.  No environment variables to set, no configuration to be made.

**Comment by mithro** [comment]
I wasn't suggesting *using* setup tools - more following their example with a `litex.cfg` type file? 

> The way lxbuilder.py works is by foisting responsibility off onto the calling program.
> 
> In this repo, netv2mvp.py is the primary entrypoint. In https://github.com/xobs/ws2812b-catcher the main entrypoint is ws2812b-catcher.py. Each script has an LX_DEPENDENCIES variable in it that lxbuildenv looks for to figure out what requirements there are.

I'm a little unclear -- do you run the `lxbuildenv.py` tool or the `netv2mvp.py` file? 

It's very weird that a definition inside the `netv2mvp.py` file is accessed from the `lxbuildenv.py` file just by having it be imported. A more normal approach would be something like;
```
import lxbuildenv
lxbuildenv.init({<config goes here>)
```

> Finally, I wanted to be able to work on submodules such as litex while they're under version control, without having to edit something in a site-dist directory. lxbuildenv

That is also my preferred method and how litex-buildenv does it. 

Currently it uses sub-modules but I'm not sure they are the right approach as opposed to just having git checkouts and managing the revision values separately... Would make it much easier to do things like Travis-CI where I have to do this horrible hack to make fetching from a person own submodules actually work -> https://github.com/timvideos/litex-buildenv/blob/master/.travis/add-local-submodule.sh

**Comment by xobs** [comment]
> I'm a little unclear -- do you run the `lxbuildenv.py` tool or the `netv2mvp.py` file?

Normally you run `netv2mvp.py`, because that's what you're building.  If you had a hypothetical project with both arty and opsis, you'd run `arty-project.py` or `opsis-project.py`.  The `lxbuildenv.py` module just allows it to work.

You can, however, run `lxbuildenv.py` to create a new build environment.  I'm still unsure of how I want this to work, but the idea is that it would set up a new git repo if necessary, add the dependencies if necessary, and create a template file for you.  Similar to what `npm init` and `cargo init` do.

>It's very weird that a definition inside the netv2mvp.py file is accessed from the lxbuildenv.py file just by having it be imported.

The goal here is to emulate environment variables without them being environment variables.  It grew out of an original experiment I did where I walked the AST looking for keywords such as "vexriscv" and "VivadoProgrammer" to try and guess what the requirements are.

The issue I have with adding an `init()` call is that it's a bit of a lie -- the act of importing the module automatically invokes it, because `lxbuildenv.py` actually does a re-exec of the Python interpreter after setting the `PYTHONHASHSEED` and `PYTHONPATH` environment variables.

**Comment by mithro** [comment]
We have collected a bunch of notes in a document at https://docs.google.com/document/d/1V47Zc0eyjUUGBNsJuYORdb4TqH4C1WjzrX9odX0YdZE/edit and I've started playing with some ideas based on the lxbuildenv module and the origina litex-buildenv at https://github.com/mithro/lxbe-tool

I think we can close this for now.
